spring.application.name=security

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## Enable H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://ep-little-breeze-a5wqxs8q-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lz0NeWC8ujcB
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional but recommended
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.app.jwtSecret=MySecretkey@123
spring.app.jwtExpirationMs=300000
